fix: Type mismatch aborts on OpaquePyObject (#56)
In
[#49](https://github.com/apache/tvm-ffi/pull/49#issuecomment-3331042097),
We noticed an issue with `OpaquePyObject`:

```
Exception caught during TVMFFIGetTypeInfo:
Traceback (most recent call last):
  File "include/tvm/ffi/type_traits.h", line 92, in tvm::ffi::TypeTraitsBase::GetMismatchTypeInfo[abi:cxx11](TVMFFIAny const*)
  File "include/tvm/ffi/object.h", line 121, in tvm::ffi::TypeIndexToTypeKey[abi:cxx11](int)
  File "src/ffi/object.cc", line 493, in TVMFFIGetTypeInfo
  File "src/ffi/object.cc", line 193, in tvm::ffi::TypeTable::Entry* tvm::ffi::TypeTable::GetTypeEntry(int32_t)
InternalError: Check failed: (entry != nullptr) is false: Cannot find type info for type_index=74
```

where when an `OpaquePyObject` is fed into a TVM-FFI function, which
expects a different type (e.g. `int`), the entire program aborts without
proper error message inside `TVMFFIGetTypeInfo`, which uses `exit(1)`
instead of C error code.

This PR fixes this issue by registering
`TypeIndex::kTVMFFIOpaquePyObject` as a builtin type index.